// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eljpscgfdwotbjoyvxte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsanBzY2dmZHdvdGJqb3l2eHRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTkyNzcsImV4cCI6MjA3MTk3NTI3N30.LcDW6WwUSkL3HfiZA4ZZrene8877Gh_m-TqSzWX-cU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});